# Generated by Django 5.0.4 on 2024-06-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutine_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
