# Generated by Django 5.0.4 on 2024-06-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
    ]
