# Generated by Django 5.0.4 on 2024-05-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('repetitions', models.IntegerField()),
                ('exercises', models.ManyToManyField(to='exercise.exercise')),
            ],
        ),
    ]
