# Generated by Django 5.0.4 on 2024-06-10 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_rutine', '0004_initial'),
        ('rutine', '0003_alter_rutine_difficulty_level_alter_rutine_name_and_more'),
        ('trainer', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignrutine',
            name='rutine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rutine.rutine', verbose_name='Rutina'),
        ),
        migrations.AlterField(
            model_name='assignrutine',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='trainer.trainer', verbose_name='Entrenador'),
        ),
        migrations.AlterField(
            model_name='assignrutine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
