from .list_view import DifficultyLevelListView
from .detail_view import DifficultyLevelDetailView
from .delete_view import DifficultyLevelDeleteView
from .update_view import DifficultyLevelUpdateView
from .create_view import DifficultyLevelCreateView
