# Generated by Django 5.0.4 on 2024-06-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muscle_exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muscleexercise',
            options={'ordering': ['name'], 'verbose_name': 'Musculo', 'verbose_name_plural': 'Musculos'},
        ),
    ]
