# Generated by Django 5.0.4 on 2024-05-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('difficulty_level', '0001_initial'),
        ('exercise', '0001_initial'),
        ('rutine_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('difficulty_level', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='difficulty_level.difficultylevel')),
                ('rutine_exercises', models.ManyToManyField(to='exercise.exercise')),
                ('rutine_type', models.ManyToManyField(to='rutine_type.rutinetype')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['name'],
            },
        ),
    ]
