# Generated by Django 5.0.4 on 2024-06-06 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difficulty_level', '0001_initial'),
        ('exercise', '0002_initial'),
        ('rutine', '0002_initial'),
        ('rutine_type', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutine',
            name='difficulty_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='difficulty_level.difficultylevel', verbose_name='Nivel de Dificultad'),
        ),
        migrations.AlterField(
            model_name='rutine',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='rutine',
            name='rutine_exercises',
            field=models.ManyToManyField(to='exercise.exercise', verbose_name='Ejercicios'),
        ),
        migrations.AlterField(
            model_name='rutine',
            name='rutine_type',
            field=models.ManyToManyField(to='rutine_type.rutinetype', verbose_name='Tipo de Rutina'),
        ),
        migrations.AlterField(
            model_name='rutine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rutines', to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
        migrations.AlterField(
            model_name='rutine',
            name='user_rutine',
            field=models.ManyToManyField(related_name='user_rutines', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios de la Rutina'),
        ),
    ]
