# Generated by Django 5.0.4 on 2024-05-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('difficulty_level', '0001_initial'),
        ('exercise_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty_level', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='difficulty_level.difficultylevel')),
                ('exercise_type', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='exercise_type.exercisetype')),
            ],
        ),
    ]
