# Generated by Django 5.0.4 on 2024-06-06 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difficulty_level', '0001_initial'),
        ('exercise', '0003_alter_exercise_options'),
        ('exercise_type', '0002_alter_exercisetype_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='difficulty_level.difficultylevel'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='exercise_type.exercisetype'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='exercises', to=settings.AUTH_USER_MODEL),
        ),
    ]
