from .list_view import MuscleExerciseListView
from .detail_view import MuscleExerciseDetailView
from .create_view import MuscleExerciseCreateView
from .update_view import MuscleExerciseUpdateView
from .delete_view import MuscleExerciseDeleteView