# Generated by Django 5.0.4 on 2024-07-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_alter_trainer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='rate',
        ),
    ]
