from .lists.list_view import RutineListView
from .lists.own_list_view import OwnRutineListView 
from .lists.picked_rutine_list_view import PickedRutineListView
from .details.detail_view import RutineDetailView
from .details.own_detail_view import OwnRutineDetailView
from .details.picked_detail_view import PickedRutineDetailView
from .create_view import RutineCreateView
from .updates.update_view import RutineUpdateView
from .updates.add_exercises_view import AddExercisesView
from .pick_rutine_view import PickRutineView
from .delete_pick_rutine_view import DeletePickRutineView