# Generated by Django 5.0.4 on 2024-06-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisetype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Ejercicio', 'verbose_name_plural': 'Tipos de Ejercicios'},
        ),
    ]
